[project]
name = "camee-scrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "selenium>=4.30.0",
    "selenium-stealth>=1.0.6",
]
